# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0e7ba6829bd0c026b8ed8a8dde23ea0b0c7c537372f651c6192c0da00eb0e4ad4c3373d8dbdf42b6c4857568d31f04346e17331c9a3c79cb8cac6cdbd5fb8af

test:
  secret_key_base: 2312382feac9deaf73f6a66dd99d40ef7035e9b3ff50a17863462c88c567683bfcf08f73940771cbc639fb2811828c0f6508c57d5d0c1b03d2777f96a1fe8fd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
